spring:
    application:
        name: message-reader
server:
    port: 9001
key: alfabeta
readFileFlag: true
turbine:
  aggregator:
    clusterConfig: SAMPLE-HYSTRIX-AGGREGATE
    appConfig: SAMPLE-HYSTRIX-AGGREGATE
