spring:
    application:
        name: message-reader
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:https://eurekademo.cfapps.industrycloud-staging.siemens.com/}/eureka/
server:
    port: 9001
key: alfabeta
readFileFlag: false
