spring:
    application:
        name: message-reader
eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekademo.cfapps.industrycloud-staging.siemens.com/
server:
    port: 9001
key: alfabeta
readFileFlag: false
