spring:
    application:
        name: message-reader
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761/}/eureka/
server:
    port: 9001
key: alfabeta
readFileFlag: false
